/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ----HP--2017-----
 */
public class login1 extends javax.swing.JFrame {

    play p = new play();
    //Insert i=new Insert();
    /**
     * Creates new form login1
     */
    public String Username;
    public String EmailUser;
    public String Password;

    public login1() {
        initComponents();
        //  setSize(700, 500);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image1 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        User1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        Signin1 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        PassWord = new javax.swing.JPasswordField();
        Email1 = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        image1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WEBSITE DOWNLOADER");

        UserName.setName("UserName"); // NOI18N

        User1.setEditable(false);
        User1.setBackground(new java.awt.Color(0, 0, 0));
        User1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User1.setForeground(new java.awt.Color(255, 255, 255));
        User1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User1.setText("User name");
        User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User1ActionPerformed(evt);
            }
        });

        pass1.setEditable(false);
        pass1.setBackground(new java.awt.Color(0, 0, 0));
        pass1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        pass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass1.setText("password");
        pass1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });

        Signin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Signin1.setLabel("SIGN IN");
        Signin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signin1ActionPerformed(evt);
            }
        });

        back1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back1.setText("Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        PassWord.setName("PassWord"); // NOI18N

        Email1.setEditable(false);
        Email1.setBackground(new java.awt.Color(0, 0, 0));
        Email1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Email1.setForeground(new java.awt.Color(255, 255, 255));
        Email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email1.setText("Email");
        Email1.setToolTipText("");
        Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1ActionPerformed(evt);
            }
        });

        Email.setToolTipText("");
        Email.setName("Email"); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        clear.setText("Clear all");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" WELCOME TO WEBSITE DOWNLOADER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(User1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(Signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(User1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(Signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Signin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signin1ActionPerformed
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        p.Play();

        Username = UserName.getText();
        System.out.println(Username);
        Password = PassWord.getText();
        System.out.println(Password);
        EmailUser = Email.getText();
        System.out.println(EmailUser);
        try {
            if (fileUser()) {

                URL_u u = new URL_u();
                u.setVisible(true);
                this.setVisible(false);

            } else {

            }
        } catch (IOException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* i.creatFolder();
         i.readFile();
         i.countLines();
         i.addData(Username1.getText(), passw1.getText(),email1.getText());*/
    }//GEN-LAST:event_Signin1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        p.Play();
        // TODO add your handling code here:
        login back = new login();
        back.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_back1ActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User1ActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        UserName.setText("");
        Email.setText("");
        PassWord.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Email1ActionPerformed

    public boolean fileUser() throws IOException {

        createFolderUsers();
        File NewUserAccount = new File("Users\\" + Username + ".uslo");

        if (NewUserAccount.exists()) {

            JOptionPane.showMessageDialog(this, "This Username " + "\"" + Username + "\"" + "Is Already Exist");
            return false;

        } else if (Username.isEmpty() || Password.isEmpty() || EmailUser.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Your Info Is Not Completed");
            return false;

        } else {

            NewUserAccount.createNewFile();
            createNewUserAccount();
            return true;
        }

    }

    public void createFolderUsers() {

        String Path = "Users";
        File Folder = new File(Path);
        if (!Folder.exists()) {

            if (Folder.mkdir()) {

                System.out.println("created Folder");

            } else {

                System.out.println("There Is Something Wrong");

            }

        } else {

            System.out.println("Folder Users Is Exist");

        }

    }

    public void createNewUserAccount() throws IOException {

        FileWriter UserAccount = new FileWriter("Users\\" + Username + ".uslo");
        //System.out.print(Username + "\n" + EmailUser + "\n" + Password);
        UserAccount.write(Username + "\n" + EmailUser + "\n" + Password);
        UserAccount.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Email1;
    private javax.swing.JPasswordField PassWord;
    private javax.swing.JButton Signin1;
    private javax.swing.JTextField User1;
    private javax.swing.JTextField UserName;
    private javax.swing.JButton back1;
    private javax.swing.JButton clear;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pass1;
    // End of variables declaration//GEN-END:variables

}
