/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ----HP--2017-----
 */
public class login extends javax.swing.JFrame {

    public String Username;
    public String Password;

    play p = new play();
    //Insert i=new Insert();
    /**
     * Creates new form login
     */
    JPanel backgroundpanel;
    JLabel backgroundimage;

    public login() {
        setSize(700, 500);
        initComponents();

        setLocationRelativeTo(null);
        //setSize(653, 354);

        // this.setLocationRelativeTo(null);
        //backgroundpanel=new JPanel();
        // backgroundimage=new JLabel(new ImageIcon(this.getClass().getResource("/project1/a.png")));
        // backgroundpanel.setPreferredSize(new Dimension(600,350));
        // backgroundimage.setBounds(0,0,1200,700);
        //add(backgroundimage);
        //add(backgroundpanel);
        // pack();
        // setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        create_account = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        User = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        passw = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        clear_all = new javax.swing.JButton();
        UseR = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WEBSITE DOWNLOADER");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setToolTipText("");
        login.setLabel("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 170, 43));

        create_account.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        create_account.setForeground(new java.awt.Color(255, 255, 255));
        create_account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_account.setText("Create an account ");
        create_account.setToolTipText("");
        jPanel1.add(create_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 260, -1));

        signin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signin.setText("SIGN IN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 150, 40));

        User.setEditable(false);
        User.setBackground(new java.awt.Color(0, 0, 0));
        User.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User.setText("User Name");
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, -1));

        pass.setEditable(false);
        pass.setBackground(new java.awt.Color(0, 0, 0));
        pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setText("password");
        pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, -1));

        passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwActionPerformed(evt);
            }
        });
        jPanel1.add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" WELCOME TO WEBSITE DOWNLOADER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 44, 480, 40));

        clear_all.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear_all.setText("Clear all");
        clear_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_allActionPerformed(evt);
            }
        });
        jPanel1.add(clear_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        UseR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseRActionPerformed(evt);
            }
        });
        jPanel1.add(UseR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 280, 30));
        UseR.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        setCursor(new Cursor(Cursor.HAND_CURSOR));

        p.Play();

        Username = UseR.getText();
        Password = passw.getText();
        try {
            loginAction();
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed

        p.Play();
        login1 b1 = new login1();
        b1.setVisible(true);
        this.setVisible(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));

// TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwActionPerformed

    private void clear_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_allActionPerformed
        //    Username.setText("");
        UseR.setText("");
        passw.setText("");
    }//GEN-LAST:event_clear_allActionPerformed

    private void UseRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UseRActionPerformed
    public void loginAction() throws IOException {

        Scanner reader;
        String password = null;
        
        File UserFile = new File("Users\\" + Username + ".uslo");
        try {

            if (UserFile.exists()) {
                reader = new Scanner(UserFile);
                while (reader.hasNext()) {
                    reader.nextLine();
                    reader.nextLine();
                    password = reader.nextLine();
                }
                if (varifid(password)) {

                        URL_u u = new URL_u();
                        u.setVisible(true);
                        this.setVisible(false);
                        u.getMouseListeners();

                    } else {

                        JOptionPane.showMessageDialog(this, "Username or Password is Incorrect");

                    }
            } else {

                JOptionPane.showMessageDialog(this, "Incorrect User Names");

            }

        } catch (FileNotFoundException ex) {

        }

    }

    public boolean varifid(String pass) {

        return pass.equals(Password);

    }

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UseR;
    private javax.swing.JTextField User;
    private javax.swing.JButton clear_all;
    private javax.swing.JLabel create_account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton login;
    private javax.swing.JTextField pass;
    private javax.swing.JPasswordField passw;
    private javax.swing.JButton signin;
    // End of variables declaration//GEN-END:variables

}
